frontend/urls.py
from django.urls import path
from .views import IndexView, network, updates, update_system

app_name = 'frontend'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('network/', network, name='network'),
    path('updates/', updates, name='updates'),
    path('update-system-confirmed/', update_system, name='update_system')
]

homeguard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('vision/', include('vision.urls', namespace='vision')),

]

vision/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import camera_usb_streaming

app_name = "vision"
urlpatterns = [
    path("camera-usb-streaming/", camera_usb_streaming, name="camera_usb_streaming"),

    path("camera-usb-iframe/", TemplateView.as_view(template_name="camera-usb.html"),
         name='camera_usb_iframe'),
    ]

frontend/models.py
from django.db import models

# Create your models here.

vision/models.py
from django.db import models

# Create your models here.

frontend/views.py
import subprocess
from time import sleep

from django.shortcuts import render
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "frontend/index.html"


def network(request):
    # 'wlan0' for RPi and 'wlp5s0' for my laptop
    result_of_iwconfig = subprocess.run(['iwconfig', 'wlan0'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    result_of_ifconfig_eth0 = subprocess.run(['ifconfig', 'eth0'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    result_of_ifconfig_wlan0 = subprocess.run(['ifconfig', 'wlan0'], stdout=subprocess.PIPE).stdout.decode('utf-8')

    list_with_iwconfig_data = result_of_iwconfig.split('\n')
    list_with_ifconfig_data_eth0 = result_of_ifconfig_eth0.split('\n')
    list_with_ifconfig_data_wlan0 = result_of_ifconfig_wlan0.split('\n')

    network_dict = {}

    for item in list_with_iwconfig_data:
        if 'SSID' in item:
            network_dict['name'] = item[item.find('\"')+1: item.rfind('\"')]
        if 'Frequency' in item:
            network_dict['Frequency'] = item[item.find('Frequency')+10: item.rfind('Hz')+2]
        if 'Rate' in item:
            network_dict['BitRate'] = item[item.find('Rate')+5: item.rfind('b/s')+3]
        if 'Quality' in item:
            network_dict['LinkQuality'] = item[item.find('Quality')+8: item.find('=')+6]

    for item in list_with_ifconfig_data_eth0:
        if 'broadcast' in item:
            network_dict['wired_ip'] = item[item.find('inet')+4: item.rfind('netmask')-1]

    for item in list_with_ifconfig_data_wlan0:
        if 'broadcast' in item:
            network_dict['wireless_ip'] = item[item.find('inet')+4: item.rfind('netmask')-1]
    return render(request, 'frontend/network.html', {'network_dict': network_dict})


def updates(request):
    return render(request, 'frontend/updates.html')


def update_system(request):
    sleep(5)
    subprocess.run(['bash', '-c', 'source /home/pi/Scripts/updates.sh'])
    return render(request, 'frontend/confirmation-system-update.html')

vision/views.py
import subprocess

from django.views.decorators import gzip
from django.views.decorators.clickjacking import xframe_options_exempt
from django.http import StreamingHttpResponse, HttpResponseServerError

import cv2
import threading
from time import sleep


class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0)
        if not self.video:
            print("Can't instantiate VideoCapture")
        self.video.set(3, 640)
        self.video.set(4, 480)
        sleep(2.0)
        (self.grabbed, self.frame) = self.video.read()
        if not self.grabbed:
            print("Can't open camera")
        threading.Thread(target=self.update, args=()).start()

    def __del__(self):
        self.video.release()
        cv2.destroyAllWindows()

    def get_frame(self):
        image = self.frame
        _, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

    def update(self):
        while True:
            (self.grabbed, self.frame) = self.video.read()


def gen(camera):
    while True:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@gzip.gzip_page
@xframe_options_exempt
def camera_usb_streaming(request):
    try:
        if cv2.VideoCapture(0).isOpened():
            print("VC open")
            cv2.VideoCapture(0).release()
        else:
            print("VC closed!!")
        cam = VideoCamera()
        return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        print("Something went wrong!")

frontend/templates/confirmation-system-update.html
{%  extends 'base.html' %}
{%  load static  %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Updates</h1>

        <div class="jumbotron jumbotron-fluid">
             <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-arrow-circle-up fa-4x mb-4 align-self-center"></i>
                    <h1 class="display-6 align-self-center">&#9989; Your operating system is up-to-date!</h1>
             </div>
        </div>

{% endblock content %}

frontend/templates/frontend/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Home Guard </title>
        <link href="{%  static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{%  static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" crossorigin="anonymous" />
        <link href="{%  static 'css/custom.css' %}" rel="stylesheet" crossorigin="anonymous" />
        <script src="{%  static 'fontawesome-free-5.15.3-web/js/all.min.js' %}" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{%  static 'academicons-1.9.1/css/academicons.min.css' %}"/>
        <link rel='shortcut icon' type='image/png' href="{%  static 'images/favicon.ico' %}" />
    </head>
    <body
        class="sb-nav-fixed"
        {%  block bodystyle %}
        {%  endblock bodystyle %}
    >
        <nav class="sb-topnav navbar navbar-expand navbar-dark sb-sidenav-dark">
            <a class="navbar-brand" href="{%  url 'frontend:index' %}">
                <span class="font-weight-bolder"><i class="fas fa-home fa-2x"></i></span>
            </a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading text-success "><h5>Devices</h5></div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-video"></i></div>
                                Cameras
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'vision:camera_usb_iframe' %}">Camera USB</a>
                                    <a class="nav-link" href="../../tips/">Camera EZVIZ (WiFi) </a>
                                    <a class="nav-link" href="../../tips/">Camera Edimax (WiFi + LAN)</a>
                                    <a class="nav-link" href="../../tips/">Camera OverMax (WiFi)</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts2" aria-expanded="false" aria-controls="collapseLayouts2">
                                <div class="sb-nav-link-icon"><i class="fas fa-weight"></i></div>
                                Sensors
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts2" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="../../tasks-serwisy-www/">Temperature</a>
                                    <a class="nav-link" href="../../tasks-internet-apps/">Humidity</a>
                                    <a class="nav-link" href="../../tasks-ml-intro/">Smog</a>
                                </nav>
                            </div>

                            <div class="sb-sidenav-menu-heading text-success"><h5>System</h5></div>
                            <a class="nav-link" href="../../grades/">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Load
                            </a>
                            <a class="nav-link" href="{% url 'frontend:updates' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-arrow-up"></i></div>
                                Updates
                            </a>
                            <a class="nav-link" href="{%  url 'frontend:network' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-wifi"></i></div>
                                Network
                            </a>
                            <a class="nav-link" href="../../about/">
                                <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                                Settings
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    {% block content %}

                    {%  endblock content %}
                </main>
                <footer class="py-4 sb-sidenav-dark mt-auto text-center">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center small">
                            <div class="text-center">
                                <span>
                                    <span class="col-2 center ai-case text-white">
                                        <a href="https://scientificdev.net/" target="_blank"><i class="fas fa-book fa-3x"></i></a>
                                    </span>
                                    <span class="col-2 center ai-case text-white">
                                        <a href="https://github.com/zacniewski" target="_blank"><i class="fab fa-github fa-3x"></i></a>
                                    </span>
                                    <span class="col-2 center ai-case text-white">
                                        <a href="https://informatyka-amw.slack.com/" target="_blank"><i class="fab fa-slack fa-3x"></i></a>
                                    </span>
                                    <span class="col-2 center ai-case text-white">
                                        <a href="https://www.facebook.com/artur.zacniewski" target="_blank"><i class="fab fa-facebook fa-3x"></i></a>
                                    </span>
                                </span>

                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

frontend/templates/frontend/confirmation-system-update.html
{%  extends 'frontend/base.html' %}
{%  load static  %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Updates</h1>

        <div class="jumbotron jumbotron-fluid">
             <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-arrow-circle-up fa-4x mb-4 align-self-center"></i>
                    <h1 class="display-6 align-self-center">&#9989; Your operating system is up-to-date!</h1>
             </div>
        </div>

{% endblock content %}

frontend/templates/frontend/index.html
{%  extends 'frontend/base.html' %}
{%  load static  %}

{% block bodystyle %}
    style="background-color: #e9ecef;"
{%  endblock bodystyle %}

{%  block content %}

    <div class="container text-center mb-5 mt-4 p-5">
        <h3 class="display-3 font-weight-bold">Home Guard system</h3>
    </div>
    <div class="d-flex flex-row justify-content-around align mt-5">
      <div class="p-2">
          <img class="mx-auto d-block w-50 mb-4 mt-4"
               src="{% static 'images/Raspberry_Pi_Logo.svg' %}"
          />
      </div>
      <div class="d-flex flex-wrap p-2">
          <ul class="text-dark display-4 list-unstyled text-justify">
              <li class="mb-4">&#9989; Based on Raspberry Pi 4</li>
              <li class="mb-4">&#9989; Works with different cameras</li>
              <li class="mb-4">&#9989; Allows the use of various sensors</li>
              <li class="mb-4">&#9989; Available via mobile app</li>
              <li>&#9989; Free updates</li>
          </ul>
      </div>
    </div>
{% endblock content %}

frontend/templates/frontend/network.html
{%  extends 'frontend/base.html' %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Network connections</h1>
        <div class="jumbotron jumbotron-fluid">
            <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-wifi fa-4x mb-4 align-self-center"></i>
                {%  if network_dict.Frequency %}
                    <h2 class="display-6 align-self-center">&#127796; Name of the network: <b>{{ network_dict.name }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; IP (wireless) of your device: <b>{{ network_dict.wireless_ip }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; Frequency: <b>{{ network_dict.Frequency }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; Bit rate: <b>{{ network_dict.BitRate }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; Link quality: <b>{{ network_dict.LinkQuality }}</b></h2>
                {%  else %}
                    <h2 class="display-6 align-self-center">&#10060;  Your device is <b>not connected</b> to any wireless network!</h2>
                {%  endif %}

            </div>
        </div>

        <div class="jumbotron jumbotron-fluid">
            <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-network-wired fa-4x mb-4 align-self-center"></i>
                {%  if network_dict.wired_ip %}
                    <h2 class="display-6 align-self-center">&#127796; IP (ethernet) of your device: <b>{{ network_dict.wired_ip }}</b></h2>
                {%  else %}
                    <h2 class="display-6 align-self-center">&#10060;  Your device is <b>not connected</b> to any wired network!</h2>
                {%  endif %}
            </div>
        </div>
    </div>
{% endblock content %}

frontend/templates/frontend/updates.html
{%  extends 'frontend/base.html' %}
{%  load static  %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Updates</h1>

        <div class="jumbotron jumbotron-fluid">
             <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-arrow-circle-up fa-4x mb-4 align-self-center"></i>
                <h2 class="display-6 align-self-center mb-5">&#127796; Update Home Guard application</h2>
                <h2 class="display-6 align-self-center mb-5">&#9940; Comparing date of current versions with date of Github version</h2>
                <a
                     href="{% url 'frontend:update_system' %}"
                     id="update_home_guard_button"
                     class="btn btn-primary btn-lg w-25 align-self-center mt-5"
                     role="button"
                     aria-disabled="true"
                >
                     Update Home Guard
                </a>
            </div>
        </div>

        <div class="jumbotron jumbotron-fluid">
            <div class="container d-flex flex-column align-content-center">
                <i class="fas fa-arrow-circle-up fa-4x mb-4 align-self-center"></i>
                <h2 class="display-6 align-self-center mb-5">&#127796; Update operating system (OS) of your device</h2>
                <h2 class="display-6 align-self-center mb-5">&#9940; Comparing date of current versions with date of Github version</h2>
                <a
                     href="{% url 'frontend:update_system' %}"
                     id="update_os_button"
                     class="btn btn-primary btn-lg w-25 align-self-center mt-5"
                     role="button"
                     aria-disabled="true"
                >
                     Update OS
                </a>
            </div>
        </div>
    </div>

{% endblock content %}

frontend/templates/index.html
{%  extends 'base.html' %}
{%  load static  %}

{% block bodystyle %}
    style="background-color: #e9ecef;"
{%  endblock bodystyle %}

{%  block content %}

    <div class="container text-center mb-5 mt-4 p-5">
        <h3 class="display-3 font-weight-bold">Home Guard system</h3>
    </div>
    <div class="d-flex flex-row justify-content-around align mt-5">
      <div class="p-2">
          <img class="mx-auto d-block w-50 mb-4 mt-4"
               src="{%  static 'images/Raspberry_Pi_Logo.svg' %}"
          />
      </div>
      <div class="d-flex flex-wrap p-2">
          <ul class="text-dark display-4 list-unstyled text-justify">
              <li class="mb-4">&#9989; Based on Raspberry Pi 4</li>
              <li class="mb-4">&#9989; Works with different cameras</li>
              <li class="mb-4">&#9989; Allows the use of various sensors</li>
              <li class="mb-4">&#9989; Available via mobile app</li>
              <li>&#9989; Free updates</li>
          </ul>
      </div>
    </div>
{% endblock content %}

frontend/templates/network.html
{%  extends 'base.html' %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Network connections</h1>
        <div class="jumbotron jumbotron-fluid">
            <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-wifi fa-4x mb-4 align-self-center"></i>
                {%  if network_dict.Frequency %}
                    <h2 class="display-6 align-self-center">&#127796; Name of the network: <b>{{ network_dict.name }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; IP (wireless) of your device: <b>{{ network_dict.wireless_ip }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; Frequency: <b>{{ network_dict.Frequency }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; Bit rate: <b>{{ network_dict.BitRate }}</b></h2>
                    <h2 class="display-6 align-self-center">&#127796; Link quality: <b>{{ network_dict.LinkQuality }}</b></h2>
                {%  else %}
                    <h2 class="display-6 align-self-center">&#10060;  Your device is <b>not connected</b> to any wireless network!</h2>
                {%  endif %}

            </div>
        </div>

        <div class="jumbotron jumbotron-fluid">
            <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-network-wired fa-4x mb-4 align-self-center"></i>
                {%  if network_dict.wired_ip %}
                    <h2 class="display-6 align-self-center">&#127796; IP (ethernet) of your device: <b>{{ network_dict.wired_ip }}</b></h2>
                {%  else %}
                    <h2 class="display-6 align-self-center">&#10060;  Your device is <b>not connected</b> to any wired network!</h2>
                {%  endif %}
            </div>
        </div>
    </div>
{% endblock content %}

frontend/templates/updates.html
{%  extends 'base.html' %}
{%  load static  %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Updates</h1>

        <div class="jumbotron jumbotron-fluid">
             <div class="container d-flex flex-column align-self-center">
                <i class="fas fa-arrow-circle-up fa-4x mb-4 align-self-center"></i>
                <h2 class="display-6 align-self-center mb-5">&#127796; Update Home Guard application</h2>
                <h2 class="display-6 align-self-center mb-5">&#9940; Comparing date of current versions with date of Github version</h2>
                <a
                     href="{% url 'frontend:update_system' %}"
                     id="update_home_guard_button"
                     class="btn btn-primary btn-lg w-25 align-self-center mt-5"
                     role="button"
                     aria-disabled="true"
                >
                     Update Home Guard
                </a>
            </div>
        </div>

        <div class="jumbotron jumbotron-fluid">
            <div class="container d-flex flex-column align-content-center">
                <i class="fas fa-arrow-circle-up fa-4x mb-4 align-self-center"></i>
                <h2 class="display-6 align-self-center mb-5">&#127796; Update operating system (OS) of your device</h2>
                <h2 class="display-6 align-self-center mb-5">&#9940; Comparing date of current versions with date of Github version</h2>
                <a
                     href="{% url 'frontend:update_system' %}"
                     id="update_os_button"
                     class="btn btn-primary btn-lg w-25 align-self-center mt-5"
                     role="button"
                     aria-disabled="true"
                >
                     Update OS
                </a>
            </div>
        </div>
    </div>

{% endblock content %}

vision/templates/camera-usb-iframe.html
    <img src="{% url 'vision:camera_usb_streaming' %}">

vision/templates/camera-usb.html
{%  extends 'frontend/base.html' %}
{%  load static  %}

{%  block content %}
    <div class="container-fluid">
        <h1 class="mt-4 font-weight-bold">Web Camera (USB)</h1>

        <div class="jumbotron jumbotron-fluid">
            <div class="d-block mx-auto">
                <iframe
                        class="text-center mx-auto d-block"
                        src="{% url 'vision:camera_usb_streaming' %}"
                        frameborder="0"
                        width="640"
                        height="480"
                        scrolling="no"

                >
                </iframe>
            </div>

        </div>
    </div>

{% endblock content %}